/* =====================================================================
   real_band_page.js — renders the synthesised-MOF comparison on results.html.

   Data comes from real_band_data.js, which is GENERATED by
   _build/build_real_band_data.py from 3_notebooks/real_results.json. Nothing
   here is transcribed and nothing here is recomputed: every statistic the
   section states was computed in Python and written into REAL_BAND_STATS, so
   there is one place a number can be wrong rather than two.

   WHAT THIS SECTION USED TO SAY, AND WHY IT CHANGED
   It used to report four synthesised structures sitting clear of the hMOF band
   with no overlap. With 61 synthesised frameworks the separation disappears:
   the two sets share a band. The earlier four were 256-972 atoms against the
   hMOFs' 3024-6592, and Delta-alpha rises with atom count, so that comparison
   was measuring graph size. The finding is withdrawn on this page rather than
   quietly deleted, because a reader who saw the old claim deserves to be told
   it was wrong and why.

   The chart plots both sets on ONE axis. Two charts side by side would let a
   reader assume ranges match when they do not; on a shared axis the reader can
   see the overlap directly instead of taking the caption's word for it.
   ===================================================================== */
(function () {
  'use strict';

  function fmt(x, n) {
    return (x === null || x === undefined || !isFinite(x)) ? '—'
      : x.toFixed(n === undefined ? 3 : n);
  }

  /* -------------------------------------------------------------------
     One horizontal axis in delta-alpha, two bands drawn on it, every
     individual structure marked. Canvas at device pixel ratio so it stays
     sharp on a high-density screen.
     ------------------------------------------------------------------- */
  function drawComparison(cv, hmofW, realW, S) {
    if (!cv) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const w = cv.clientWidth || 900, h = cv.clientHeight || 280;
    cv.width = w * dpr; cv.height = h * dpr;
    const g = cv.getContext('2d');
    g.setTransform(dpr, 0, 0, dpr, 0, 0);
    g.clearRect(0, 0, w, h);

    const all = hmofW.concat(realW);
    const lo = Math.min.apply(null, all) - 0.06;
    const hi = Math.max.apply(null, all) + 0.06;
    const padL = 132, padR = 26, padT = 34, padB = 46;
    const X = v => padL + (v - lo) / (hi - lo) * (w - padL - padR);

    // --- the overlap region, drawn first so everything else sits on top ---
    if (S && isFinite(S.overlap_lo) && S.overlap_hi > S.overlap_lo) {
      g.fillStyle = PAL.alpha(PAL.good, 0.10);
      g.fillRect(X(S.overlap_lo), padT, X(S.overlap_hi) - X(S.overlap_lo), h - padB - padT);
      g.strokeStyle = PAL.alpha(PAL.good, 0.5); g.setLineDash([4, 3]); g.lineWidth = 1;
      g.beginPath();
      g.moveTo(X(S.overlap_lo), padT); g.lineTo(X(S.overlap_lo), h - padB);
      g.moveTo(X(S.overlap_hi), padT); g.lineTo(X(S.overlap_hi), h - padB);
      g.stroke(); g.setLineDash([]);
      g.fillStyle = PAL.good; g.font = '600 11px ui-sans-serif, system-ui';
      g.textAlign = 'center';
      g.fillText('the two ranges overlap here  ' + fmt(S.overlap_lo, 2) + '–' + fmt(S.overlap_hi, 2),
                 (X(S.overlap_lo) + X(S.overlap_hi)) / 2, padT - 12);
    }

    // --- axis ---
    g.strokeStyle = PAL.border; g.lineWidth = 1;
    g.beginPath(); g.moveTo(padL, h - padB); g.lineTo(w - padR, h - padB); g.stroke();
    g.fillStyle = PAL.text3; g.font = '11px ui-sans-serif, system-ui'; g.textAlign = 'center';
    for (let t = Math.ceil(lo * 10) / 10; t <= hi; t += 0.1) {
      const x = X(t);
      g.strokeStyle = PAL.alpha(PAL.border, 0.7);
      g.beginPath(); g.moveTo(x, padT); g.lineTo(x, h - padB); g.stroke();
      g.fillStyle = PAL.text3;
      g.fillText(t.toFixed(1), x, h - padB + 16);
    }
    g.fillText('Δα  (spectrum width)', (padL + w - padR) / 2, h - 8);

    // --- a band: full-range whisker, interquartile box, median, one dot each
    function band(y, values, colour, label, sub) {
      const s = values.slice().sort(function (a, b) { return a - b; });
      const q = f => {
        const i = (s.length - 1) * f, a = Math.floor(i), b = Math.ceil(i);
        return s[a] + (s[b] - s[a]) * (i - a);
      };
      const q1 = q(0.25), q3 = q(0.75), med = q(0.5);

      g.strokeStyle = PAL.alpha(colour, 0.55); g.lineWidth = 1.5;
      g.beginPath(); g.moveTo(X(s[0]), y); g.lineTo(X(s[s.length - 1]), y); g.stroke();

      g.fillStyle = PAL.alpha(colour, 0.16);
      g.strokeStyle = colour; g.lineWidth = 1.2;
      g.fillRect(X(q1), y - 15, X(q3) - X(q1), 30);
      g.strokeRect(X(q1), y - 15, X(q3) - X(q1), 30);

      g.strokeStyle = colour; g.lineWidth = 2.2;
      g.beginPath(); g.moveTo(X(med), y - 15); g.lineTo(X(med), y + 15); g.stroke();

      // deterministic vertical jitter so overlapping points stay countable
      g.fillStyle = PAL.alpha(colour, 0.72);
      s.forEach(function (v, i) {
        const jit = ((i * 2654435761 % 1000) / 1000 - 0.5) * 15;
        g.beginPath(); g.arc(X(v), y + jit, 2.3, 0, Math.PI * 2); g.fill();
      });

      g.textAlign = 'right';
      g.fillStyle = PAL.text; g.font = '600 12.5px ui-sans-serif, system-ui';
      g.fillText(label, padL - 14, y - 2);
      g.fillStyle = PAL.text3; g.font = '11px ui-sans-serif, system-ui';
      g.fillText(sub, padL - 14, y + 13);
      g.textAlign = 'center';
    }

    band(padT + 40, hmofW, PAL.brand, 'Hypothetical', hmofW.length + ' hMOF frameworks');
    band(padT + 118, realW, PAL.node, 'Synthesised', realW.length + ' real CoRE MOFs');
  }

  function render() {
    const host = document.getElementById('real-band-body');
    if (!host || !window.REAL_BAND_DATA || !window.BAND_DATA || !window.REAL_BAND_STATS) return;

    const R = window.REAL_BAND_DATA, S = window.REAL_BAND_STATS;
    const hmofW = Object.keys(window.BAND_DATA).map(k => window.BAND_DATA[k].width);
    const names = Object.keys(R);               // already sorted widest-first by the generator
    const realW = names.map(n => R[n].width);

    // ---- table: 61 rows is too many to read, so show the extremes ----------
    // The full set is in the chart above and in real_band_data.js; a table
    // that needs scrolling to compare its own first and last row is not doing
    // the job a table is for.
    const HEAD = 6, TAIL = 4;
    const shown = names.slice(0, HEAD).concat(names.slice(-TAIL));
    let rows = '';
    shown.forEach(function (n, i) {
      if (i === HEAD) {
        rows += '<tr><td class="dt-note" colspan="7" style="text-align:center;padding:10px 0">' +
          '⋯ ' + (names.length - HEAD - TAIL) + ' further frameworks, all plotted above ⋯' +
          '</td></tr>';
      }
      const d = R[n];
      const short = n.replace(/_clean$|_manual$|_charged$/, '');
      const tag = /_manual$/.test(n) ? 'manual' : (/_charged$/.test(n) ? 'charged' : 'clean');
      rows += '<tr>' +
        '<td class="dt-label"><b>' + short + '</b>' +
          '<div style="font-size:12px;color:var(--text-3);margin-top:2px">CoRE MOF 2019 · ' + tag + '</div></td>' +
        '<td class="dt-value">' + d.N + '</td>' +
        '<td class="dt-value">' + d.n_nodes + ' / ' + d.n_linkers + '</td>' +
        '<td class="dt-value">' + d.diameter + '</td>' +
        '<td class="dt-value">' + (d.lcd === null ? '—' : fmt(d.lcd, 2)) + '</td>' +
        '<td class="dt-value"><b>' + fmt(d.width) + '</b> <span style="color:var(--text-3)">± ' +
          fmt(d.width_sd, 3) + '</span></td>' +
        '<td class="dt-value">' + fmt(d.asymmetry, 2) + '</td>' +
        '</tr>';
    });

    host.innerHTML =
      '<div class="chart-box"><canvas id="real-band-canvas" style="width:100%;height:280px"></canvas></div>' +

      '<div class="callout" style="margin-top:16px"><b>The result: the two sets share a band.</b> ' +
      'The ' + S.n_hmof + ' hypothetical frameworks span Δα = ' + fmt(S.h_min, 2) + '–' + fmt(S.h_max, 2) +
      '; the ' + S.n + ' synthesised ones span ' + fmt(S.w_min, 2) + '–' + fmt(S.w_max, 2) + '. ' +
      'The ranges overlap over ' + fmt(S.overlap_lo, 2) + '–' + fmt(S.overlap_hi, 2) + ', which contains ' +
      Math.round(S.overlap_frac_real * 100) + '% of the synthesised set and ' +
      Math.round(S.overlap_frac_hmof * 100) + '% of the hypothetical one. ' +
      'The means differ by ' + fmt(S.mean_diff, 3) + ' (Welch <i>p</i> = ' + fmt(S.p_welch, 2) +
      ', Mann–Whitney <i>p</i> = ' + fmt(S.p_mannwhitney, 2) + ', Cohen\'s <i>d</i> = ' + fmt(S.cohens_d, 2) +
      '), and the 95% interval on that difference, ' + fmt(S.ci95_lo, 3) + ' to ' + fmt(S.ci95_hi, 3) +
      ', straddles zero. Mean asymmetry is ' + fmt(S.asym_real, 2) + ' against ' + fmt(S.asym_hmof, 2) +
      ' — the spectra are not merely the same width, they are the same shape.</div>' +

      '<div class="callout warn" style="margin-top:14px"><b>One difference that is real: the spread.</b> ' +
      'The synthesised set has standard deviation ' + fmt(S.w_sd, 3) + ' against ' + fmt(S.h_sd, 3) +
      ' for the hypothetical one (Levene <i>p</i> = ' + fmt(S.p_levene, 3) + '). Frameworks that people ' +
      'actually made are more structurally varied than frameworks one algorithm generated — which is ' +
      'what you would expect, and it is the opposite of the usual worry that a curated set is the narrow one.</div>' +

      '<div class="callout bad" style="margin-top:14px"><b>Withdrawn: the earlier four-structure claim.</b> ' +
      'This section previously reported HKUST-1, UiO-66, MOF-5 and ZIF-8 at Δα = 1.66–2.26, clear of the ' +
      'hMOF band with no overlap. That is withdrawn. Those four were expanded to 256–972 atoms, while the ' +
      S.n_hmof + ' hMOFs occupy ' + S.hN_min + '–' + S.hN_max + ' — not one hMOF is as small as the largest ' +
      'of the four. Δα rises with atom count (<i>r</i> = ' + fmt(S.r_width_atoms_hmof, 2) + ' across the hMOFs), ' +
      'so the comparison was reading graph size, the same confound that killed the pore-size claim earlier in ' +
      'this project. The ' + S.n + ' frameworks here are size-matched by construction: ' + S.n_size_matched +
      ' of them are at least as large as the smallest hMOF.</div>' +

      '<div class="callout good" style="margin-top:14px"><b>The pore-size confound reproduces on real data.</b> ' +
      'Across these ' + S.n + ' synthesised frameworks Δα correlates with largest-cavity diameter at <i>r</i> = ' +
      fmt(S.r_width_lcd_real, 2) + ', which looks like a pore effect. Hold graph size constant and it falls to ' +
      fmt(S.r_width_lcd_given_size, 2) + ', while size itself holds at <i>r</i> = ' + fmt(S.r_width_atoms_real, 2) +
      '. The correlation this project withdrew on hypothetical structures fails in the same way, for the same ' +
      'reason, on structures that exist.</div>' +

      '<table class="data-table" style="margin-top:18px"><thead><tr>' +
        '<td>Framework<br><span style="font-weight:400;color:var(--text-3)">widest and narrowest</span></td>' +
        '<td>Atoms</td><td>Nodes / linkers</td><td>Diameter</td><td>LCD (Å)</td>' +
        '<td>Δα</td><td>Asymmetry A</td>' +
      '</tr></thead><tbody>' + rows + '</tbody></table>' +

      '<div class="sd" style="margin-top:10px">Source: ' + S.source + '. ' +
      'Spectra computed by the notebook pipeline; the full ' + S.n + '-row table is in ' +
      '<code>3_notebooks/real_results.json</code>.</div>';

    drawComparison(document.getElementById('real-band-canvas'), hmofW, realW, S);
  }

  function boot() {
    try { render(); } catch (e) { if (window.console) console.error('real-band section failed', e); }
    if (window.PAL && PAL.onTheme) PAL.onTheme(function () { try { render(); } catch (e) {} });
    window.addEventListener('resize', function () { try { render(); } catch (e) {} });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();

  window.MOFRealBand = { render: render };
})();
