/* =====================================================================
   real_band_page.js — renders the synthesised-MOF comparison on results.html.

   Data comes from real_band_data.js, which is GENERATED by
   build_real_band.js from the published CIFs in this folder. Nothing here is
   transcribed; if you change the pipeline, rerun the generator and these
   numbers change with it.

   The chart deliberately plots both sets on ONE axis. Two charts side by side
   would let a reader assume the ranges overlap; on a shared axis the gap is
   simply visible, which is the whole point of the section.
   ===================================================================== */
(function () {
  'use strict';

  function fmt(x, n) { return (x === null || x === undefined || !isFinite(x)) ? '—' : x.toFixed(n === undefined ? 3 : n); }

  /* -------------------------------------------------------------------
     One horizontal axis in delta-alpha, two bands drawn on it, and every
     individual structure marked. Drawn on canvas at device pixel ratio so
     it stays sharp on a high-density screen.
     ------------------------------------------------------------------- */
  function drawComparison(cv, hmofW, realData) {
    if (!cv) return;
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const w = cv.clientWidth || 900, h = cv.clientHeight || 260;
    cv.width = w * dpr; cv.height = h * dpr;
    const g = cv.getContext('2d');
    g.setTransform(dpr, 0, 0, dpr, 0, 0);
    g.clearRect(0, 0, w, h);

    const realW = Object.keys(realData).map(k => realData[k].width);
    const all = hmofW.concat(realW);
    const lo = Math.min.apply(null, all) - 0.08;
    const hi = Math.max.apply(null, all) + 0.08;
    const padL = 128, padR = 26, padT = 26, padB = 44;
    const X = v => padL + (v - lo) / (hi - lo) * (w - padL - padR);

    // --- axis ---
    g.strokeStyle = PAL.border; g.lineWidth = 1;
    g.beginPath(); g.moveTo(padL, h - padB); g.lineTo(w - padR, h - padB); g.stroke();
    g.fillStyle = PAL.text3; g.font = '11px ui-sans-serif, system-ui'; g.textAlign = 'center';
    for (let t = Math.ceil(lo * 10) / 10; t <= hi; t += 0.2) {
      const x = X(t);
      g.strokeStyle = PAL.alpha(PAL.border, 0.9);
      g.beginPath(); g.moveTo(x, padT); g.lineTo(x, h - padB); g.stroke();
      g.fillText(t.toFixed(1), x, h - padB + 16);
    }
    g.fillText('Δα  (spectrum width)', (padL + w - padR) / 2, h - 8);

    // --- a band: an interquartile box, a full-range whisker, one dot per member
    function band(y, values, colour, label, sub) {
      const s = values.slice().sort(function (a, b) { return a - b; });
      const q = f => { const i = (s.length - 1) * f, a = Math.floor(i), b = Math.ceil(i);
                       return s[a] + (s[b] - s[a]) * (i - a); };
      const q1 = q(0.25), q3 = q(0.75), med = q(0.5);

      g.strokeStyle = PAL.alpha(colour, 0.55); g.lineWidth = 1.5;
      g.beginPath(); g.moveTo(X(s[0]), y); g.lineTo(X(s[s.length - 1]), y); g.stroke();

      g.fillStyle = PAL.alpha(colour, 0.16);
      g.strokeStyle = colour; g.lineWidth = 1.2;
      g.fillRect(X(q1), y - 15, X(q3) - X(q1), 30);
      g.strokeRect(X(q1), y - 15, X(q3) - X(q1), 30);

      g.strokeStyle = colour; g.lineWidth = 2.2;
      g.beginPath(); g.moveTo(X(med), y - 15); g.lineTo(X(med), y + 15); g.stroke();

      g.fillStyle = PAL.alpha(colour, 0.75);
      s.forEach(function (v) {
        g.beginPath(); g.arc(X(v), y, 2.4, 0, Math.PI * 2); g.fill();
      });

      g.textAlign = 'right';
      g.fillStyle = PAL.text; g.font = '600 12.5px ui-sans-serif, system-ui';
      g.fillText(label, padL - 14, y - 2);
      g.fillStyle = PAL.text3; g.font = '11px ui-sans-serif, system-ui';
      g.fillText(sub, padL - 14, y + 13);
      g.textAlign = 'center';
      return { lo: s[0], hi: s[s.length - 1] };
    }

    const a = band(padT + 34, hmofW, PAL.brand, 'Hypothetical', String(hmofW.length) + ' hMOF frameworks');
    const b = band(padT + 104, realW, PAL.node, 'Synthesised', String(realW.length) + ' real MOFs');

    // --- the gap between them, annotated, because it is the finding --------
    const gapLo = Math.min(a.hi, b.hi), gapHi = Math.max(a.lo, b.lo);
    if (gapHi > gapLo) {
      g.fillStyle = PAL.alpha(PAL.warn, 0.10);
      g.fillRect(X(gapLo), padT, X(gapHi) - X(gapLo), h - padB - padT);
      g.strokeStyle = PAL.alpha(PAL.warn, 0.6); g.setLineDash([4, 3]); g.lineWidth = 1;
      g.beginPath(); g.moveTo(X(gapLo), padT); g.lineTo(X(gapLo), h - padB);
      g.moveTo(X(gapHi), padT); g.lineTo(X(gapHi), h - padB); g.stroke();
      g.setLineDash([]);
      g.fillStyle = PAL.warn; g.font = '600 11px ui-sans-serif, system-ui';
      g.fillText('gap ' + (gapHi - gapLo).toFixed(2), (X(gapLo) + X(gapHi)) / 2, padT + 12);
    }
  }

  function render() {
    const host = document.getElementById('real-band-body');
    if (!host || !window.REAL_BAND_DATA || !window.BAND_DATA) return;

    const R = window.REAL_BAND_DATA, RS = window.REAL_BAND_STATS;
    const hmofW = Object.keys(window.BAND_DATA).map(k => window.BAND_DATA[k].width);
    const names = Object.keys(R);

    // ---- table -----------------------------------------------------------
    let rows = '';
    names.forEach(function (n) {
      const d = R[n];
      rows += '<tr>' +
        '<td class="dt-label"><b>' + n + '</b><div style="font-size:12px;color:var(--text-3);margin-top:2px">' +
          d.reference + '</div></td>' +
        '<td class="dt-value">' + d.metal + '</td>' +
        '<td class="dt-value">' + d.net + '</td>' +
        '<td class="dt-value">' + d.cn_computed + ' / ' + d.cn_published +
          (d.cn_match ? ' <b style="color:var(--good)">✓</b>' : ' <b style="color:var(--bad)">✗</b>') + '</td>' +
        '<td class="dt-value">' + d.supercellN + '³ → ' + d.N + '</td>' +
        '<td class="dt-value"><b>' + fmt(d.width) + '</b></td>' +
        '<td class="dt-value">' + fmt(d.asymmetry, 2) + '</td>' +
        '</tr>';
    });

    const hLo = Math.min.apply(null, hmofW), hHi = Math.max.apply(null, hmofW);
    const gap = RS.w_min - hHi;

    host.innerHTML =
      '<div class="chart-box"><canvas id="real-band-canvas" style="width:100%;height:260px"></canvas></div>' +
      '<table class="data-table" style="margin-top:18px"><thead><tr>' +
        '<td>Structure</td><td>Metal</td><td>Net</td><td>Coordination<br>computed / published</td>' +
        '<td>Supercell → blocks</td><td>Δα</td><td>Asymmetry A</td>' +
      '</tr></thead><tbody>' + rows + '</tbody></table>' +
      (RS.cn_all_match
        ? '<div class="callout good" style="margin-top:16px"><b>The decomposition is verified before the spectrum is trusted.</b> ' +
          'Every one of these structures reproduces its published coordination number exactly — including UiO-66 at 12, ' +
          'which the non-periodic construction reports as 1. A spectrum computed from a wrong graph would be a wrong number ' +
          'that still looks plausible, so this check runs first.</div>'
        : '<div class="callout bad" style="margin-top:16px"><b>Coordination mismatch — do not trust these spectra.</b></div>') +
      '<div class="callout warn" style="margin-top:14px"><b>The result: the two sets do not overlap.</b> ' +
      'The 77 hypothetical frameworks span Δα = ' + fmt(hLo, 2) + '–' + fmt(hHi, 2) + '. ' +
      'The synthesised structures span ' + fmt(RS.w_min, 2) + '–' + fmt(RS.w_max, 2) + ', ' +
      'clear of the hMOF range by ' + fmt(gap, 2) + ' with no overlap at all. ' +
      'This is not a size artefact: MOF-5 has the <i>same</i> Zn₄O node as all 77 and the same 256 blocks as 48 of them, ' +
      'and still lands at ' + fmt(R['MOF-5'] ? R['MOF-5'].width : NaN, 2) + '. ' +
      'Across the 77, Δα correlates with block count at only r = 0.11, so graph size does not explain the gap either.</div>';

    drawComparison(document.getElementById('real-band-canvas'), hmofW, R);
  }

  function boot() {
    try { render(); } catch (e) { if (window.console) console.error('real-band section failed', e); }
    if (window.PAL && PAL.onTheme) PAL.onTheme(function () { try { render(); } catch (e) {} });
    window.addEventListener('resize', function () { try { render(); } catch (e) {} });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();

  window.MOFRealBand = { render: render };
})();
