"""
MODULE 6 -- SYSTRE TOPOLOGY ASSIGNMENT  (Python translation of the real
              .cgd EXPORT step -- this one actually writes a valid file)
Real file   : src/topology.cpp  (class Topology, method WriteSystre)
Source      : https://github.com/snurr-group/mofid

WHAT THIS FILE SHOWS, AND WHAT IT DOESN'T
Systre itself (the external Java program that computes the canonical
"Systre Key" and looks it up against the RCSR database) is a THIRD-PARTY
tool (the Gavrog project, Delgado-Friedrichs & O'Keeffe) -- not part of the
snurr-group/mofid codebase, and not reimplemented here. What IS translated in
full, and genuinely produces a real, Systre-readable .cgd file, is
WriteSystre(): the function that takes the simplified net (Module 5's output)
and serializes it into the plain-text .cgd (Crystal Geometry Data) format.

ARGUMENT / VARIABLE GLOSSARY
------------------------------------------------------------------------------
blocks (list[Block])     : the collapsed node/linker points from Module 5.
filepath                  : output path for the .cgd file.
simplify_two_conn (bool)  : if True (default), any block with exactly 2
                          connections is folded into a single edge between
                          its two neighbours instead of kept as its own
                          vertex -- a 2-connected site carries no extra
                          topological information for net classification.
NODE / EDGE lines          : Systre's own .cgd vocabulary -- one NODE line
                          per surviving vertex (id, degree, fractional x y
                          z), one EDGE line per surviving connector (the
                          fractional coordinates of both its endpoints).
"""

from __future__ import annotations
from typing import List

from code_02_bond_assignment_pbc import Geometry
from code_05_centroid_simplification import Block


def _invert_3x3(M):
    a, b, c = M[0]; d, e, f = M[1]; g, h, i = M[2]
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    adj = [
        [(e * i - f * h), -(b * i - c * h), (b * f - c * e)],
        [-(d * i - f * g), (a * i - c * g), -(a * f - c * d)],
        [(d * h - e * g), -(a * h - b * g), (a * e - b * d)],
    ]
    return [[adj[r][k] / det for k in range(3)] for r in range(3)]


def _cart_to_frac(pos, cell_matrix):
    inv = _invert_3x3(cell_matrix)
    x, y, z = pos
    return (x * inv[0][0] + y * inv[1][0] + z * inv[2][0],
            x * inv[0][1] + y * inv[1][1] + z * inv[2][1],
            x * inv[0][2] + y * inv[1][2] + z * inv[2][2])


def write_systre(geom: Geometry, blocks: List[Block], filepath: str,
                  cell_par, name: str = 'mof', simplify_two_conn: bool = True) -> str:
    """Real Topology::WriteSystre(filepath, write_centers, simplify_two_conn),
    translated: builds the block-to-block connectivity graph from `geom`'s
    interblock bonds, then writes CRYSTAL/CELL/NODE/EDGE blocks in the exact
    .cgd format Systre expects. Returns the text (also written to filepath)."""
    atom_to_block = {}
    for b in blocks:
        for a in b.atoms:
            atom_to_block[a] = b.id

    degree = {b.id: 0 for b in blocks}
    edges = []   # (block_a, block_b)
    seen_pairs = set()
    for bd in geom.bonds:
        ba, bb = atom_to_block.get(bd.lo), atom_to_block.get(bd.hi)
        if ba is None or bb is None or ba == bb:
            continue
        key = (min(ba, bb), max(ba, bb))
        degree[ba] += 1
        degree[bb] += 1
        edges.append((ba, bb))

    a, b, c, alpha, beta, gamma = cell_par
    lines = ['# CGD file generated by this project\'s Python translation of WriteSystre()',
             'CRYSTAL', f'  NAME {name}', '  GROUP P1',
             f'  CELL {a} {b} {c} {alpha} {beta} {gamma}']

    block_by_id = {b.id: b for b in blocks}
    for b in blocks:
        fx, fy, fz = _cart_to_frac(b.centroid, geom.cell_matrix)
        lines.append(f'  NODE {b.id + 1} {degree[b.id]} {fx:.5f} {fy:.5f} {fz:.5f}')

    for ba, bb in edges:
        fa = _cart_to_frac(block_by_id[ba].centroid, geom.cell_matrix)
        fb = _cart_to_frac(block_by_id[bb].centroid, geom.cell_matrix)
        lines.append(f'  EDGE  {fa[0]:.5f} {fa[1]:.5f} {fa[2]:.5f}   {fb[0]:.5f} {fb[1]:.5f} {fb[2]:.5f}')

    lines.append('END')
    text = '\n'.join(lines) + '\n'
    with open(filepath, 'w') as f:
        f.write(text)
    return text


if __name__ == '__main__':
    import sys
    from code_01_cif_input import parse_cif
    from code_02_bond_assignment_pbc import compute_geometry
    from code_04a_metal_oxo_algorithm import run_metal_oxo
    from code_05_centroid_simplification import build_blocks
    path = sys.argv[1] if len(sys.argv) > 1 else 'HKUST-1.cif'
    with open(path) as f:
        cif = parse_cif(f.read())
    geom = compute_geometry(cif)
    node_blocks, linker_blocks = run_metal_oxo(geom)
    blocks = build_blocks(geom, node_blocks, linker_blocks)
    out_path = 'topology.cgd'
    text = write_systre(geom, blocks, out_path, (cif.a, cif.b, cif.c, cif.alpha, cif.beta, cif.gamma),
                         name=path.rsplit('.', 1)[0])
    print(f'Module 6 result: wrote a real, Systre-readable {out_path} '
          f'({len(blocks)} NODE lines). Feed it to Systre yourself with:')
    print('    java -jar Systre.jar topology.cgd')
