#!/usr/bin/env python3
"""
Derives real_mof_band.ipynb from mof_band_analysis.ipynb.

WHY DERIVE RATHER THAN WRITE A NEW NOTEBOOK
The scientific claim is that the hypothetical and the real frameworks were put
through the *identical* pipeline. If the two notebooks were written separately
they would drift, and the comparison would quietly stop being valid. So every
analysis cell here is copied byte-for-byte from the notebook that produced the
77-framework band. Only four things change:

  * the title,
  * Step 2, which is where the wrong data came from,
  * the output filename, so a real run cannot overwrite the hMOF results,
  * three new cells at the end that compare the two sets and export figures.
"""
import json, copy, sys

SRC = 'mof_band_analysis.ipynb'
DST = 'real_mof_band.ipynb'

nb = json.load(open(SRC, encoding='utf-8'))
cells = nb['cells']


def md(text):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': text.splitlines(keepends=True)}


def code(text):
    return {'cell_type': 'code', 'metadata': {}, 'execution_count': None,
            'outputs': [], 'source': text.splitlines(keepends=True)}


# ---------------------------------------------------------------- title -----
cells[0] = md('''# Multifractal spectra of **real, experimentally synthesised** MOFs

This notebook is the twin of `mof_band_analysis.ipynb`. Every analysis cell is
identical — same bonding rule, same supercell rule, same influential-node
selection, same τ definition, same q grid. Only the **data source** differs.

## Why this notebook exists

The 77-framework band was computed on **hMOF** structures: chemically sound, but
generated by a program and never made in a laboratory. That happened by
accident. The original notebook asked MOFX-DB for `CoREMOF 2019` and received
hMOF records instead, because on that endpoint the `database=` parameter is
advisory and loses to the `gases[]` filter when both are supplied. The request
was right; the response did not honour it.

A provenance check further down the original notebook caught it and printed a
warning. That warning is the only reason the project did not publish
"experimental" results computed on generated structures.

## What changed

Step 2 now **filters every returned record on its own `database` field** and
discards anything that is not CoRE MOF, rather than trusting the server. It also
prints how many records were streamed, how many were kept, and what was thrown
away — so the provenance claim is checkable rather than asserted.

If the live query fails or the service is unreachable, Step 2 falls back to
reading CIF files from a local folder, so this notebook still runs.

## What to do with the output

The final cell writes **`real_results.json`** and a set of figures. Send
`real_results.json` back and it goes straight onto the Results page of the
project site alongside the 77-framework band.

**Runtime:** roughly 15–25 minutes for 50 frameworks on a free Colab CPU
instance. The expensive part is the all-pairs shortest-path computation on each
supercell, which is `O(N²)` in memory and `O(N·E)` in time.
''')

# --------------------------------------------------------------- step 2 -----
cells[3] = md('''## Step 2 — Query MOFX-DB for real CoRE MOF structures, and **verify** what comes back

The fix is the `_is_target_db()` filter: each record is checked against the
database it says it came from, and anything that is not CoRE MOF is discarded
before it can reach the analysis.
''')

cells[4] = code('''# ============================================================
# STEP 2: Live query against MOFX-DB — with a hard client-side provenance filter
# ============================================================
# THE BUG THIS FIXES
# The previous run asked for database="CoREMOF 2019" and got hMOF records back.
# On this endpoint the database= parameter is advisory: when it is combined with
# a gases[] filter, the gas filter wins and the database filter is ignored. The
# request was correct and the response was wrong, which is the worst combination
# because nothing errors -- you just silently analyse the wrong material class.
#
# THE FIX
# Trust nothing the server says about what it sent. Check every record against
# its own `database` field and throw away anything that does not match. This is
# the difference between "we asked for real MOFs" and "these are real MOFs".
!pip install -q mofdb-client 2>/dev/null || pip install -q --break-system-packages mofdb-client

import collections, re
from pathlib import Path

USE_LIVE_QUERY = True     # set False to skip the API and use LOCAL_CIF_DIR below
LOCAL_CIF_DIR  = Path("real_cifs")   # fallback: a folder of .cif files you supply


def _norm(s):
    """Loose comparison: 'CoREMOF 2019', 'CoRE-MOF 2019' and 'coremof2019' all match."""
    return str(s or "").lower().replace(" ", "").replace("-", "").replace("_", "")


def _is_target_db(m):
    """True only if THIS record actually comes from the database we asked for."""
    return _norm(TARGET_DATABASE) in _norm(getattr(m, "database", ""))


def fetch_real_mofs(want, hard_cap=6000):
    """Stream MOFX-DB and keep only genuine CoRE MOF records.

    want      how many verified records we need before stopping
    hard_cap  stop scanning if the server is clearly ignoring the filter
              entirely, rather than reading a very long stream to the end
    """
    from mofdb_client.main import get_all
    params = {"database": TARGET_DATABASE, "gases[]": [TARGET_GAS]}
    kept, seen, rejected = [], 0, collections.Counter()
    for m in get_all(params):
        seen += 1
        if _is_target_db(m):
            kept.append(m)
        else:
            rejected[str(getattr(m, "database", "unknown"))] += 1
        if len(kept) >= want or seen >= hard_cap:
            break
    print(f"  streamed {seen} records; kept {len(kept)} verified {TARGET_DATABASE}")
    if rejected:
        print(f"  discarded (wrong database): {dict(rejected.most_common(5))}")
    if seen >= hard_cap and len(kept) < want:
        print(f"  *** the server returned almost nothing from {TARGET_DATABASE} in "
              f"{hard_cap} records. Try dropping the gas filter (set TARGET_GAS=None).")
    return kept


candidates = []
if USE_LIVE_QUERY:
    try:
        candidates = fetch_real_mofs(want=max(80, MIN_MOFS * 2))
    except Exception as e:
        print(f"  live query failed ({type(e).__name__}: {e})")
        print(f"  falling back to local CIFs in {LOCAL_CIF_DIR}/")

# ---- fallback: a folder of CIF files ---------------------------------------
# Used if the API is unreachable, or if you would rather supply a curated set.
# Put .cif files in real_cifs/ (upload a zip and unzip it) and re-run this cell.
if not candidates:
    class _LocalMof:
        """Minimal stand-in with the same attributes Step 3 reads off a record."""
        def __init__(self, path, idx):
            self.cif = path.read_text()
            self.name = path.stem
            self.id = idx
            self.database = TARGET_DATABASE + " (local file)"
            self.mofid = self.mofkey = None
            self.url = str(path)
            self.void_fraction = self.lcd = self.pld = None
            self.isotherms = []
    if LOCAL_CIF_DIR.exists():
        files = sorted(LOCAL_CIF_DIR.glob("*.cif"))
        candidates = [_LocalMof(p, i) for i, p in enumerate(files)]
        print(f"  loaded {len(candidates)} CIFs from {LOCAL_CIF_DIR}/")
    else:
        LOCAL_CIF_DIR.mkdir(exist_ok=True)
        print(f"  created {LOCAL_CIF_DIR}/ — put .cif files there and re-run this cell")

candidates = sorted(candidates, key=lambda m: m.id)

# ---- VERIFY WHAT WE ACTUALLY HAVE ------------------------------------------
returned_dbs = collections.Counter(str(getattr(m, "database", "unknown")) for m in candidates)
print()
print(f"{len(candidates)} structures ready.")
print(f"  databases represented: {dict(returned_dbs)}")

_wrong = [db for db in returned_dbs if not _norm(TARGET_DATABASE) in _norm(db)]
assert not _wrong, (
    f"Provenance check FAILED: {_wrong} slipped through the filter. "
    f"Do not analyse this set -- fix the filter first.")
print("  provenance: every record verified as", TARGET_DATABASE)

# ---- metal diversity: the thing the hMOF set completely lacked --------------
_metals = collections.Counter()
for m in candidates:
    els = set(re.findall(r"\\[([A-Z][a-z]?)[\\]\\[]", getattr(m, "mofid", "") or ""))
    els -= {"C", "N", "O", "H", "S", "P", "Cl", "F", "Br", "I", "Si"}
    _metals[",".join(sorted(els)) or "unparsed"] += 1
print(f"  metal composition: {dict(_metals.most_common(10))}")
if len([k for k in _metals if k != "unparsed"]) <= 2:
    print("  *** NOTE: this set is effectively single-metal. Do not claim it")
    print("  *** 'cuts across different metals' -- the hMOF set failed on exactly this.")
else:
    print("  -> multi-metal set: a cross-family claim is testable on this data")

assert len(candidates) >= MIN_MOFS, (
    f"Only {len(candidates)} verified structures, below MIN_MOFS={MIN_MOFS}. "
    f"Raise the `want` argument, drop the gas filter, or supply CIFs in "
    f"{LOCAL_CIF_DIR}/. Do NOT pad this with hMOF entries.")

for m in candidates[:5]:
    print(f"  id={m.id:>7}  name={str(m.name)[:26]:<26}  db={m.database}")
print("  ...")
''')

# ------------------------------------------------- output file name ---------
for c in cells:
    if c['cell_type'] != 'code':
        continue
    src = ''.join(c['source'])
    if '_p = OUT_DIR / "results.json"' in src:
        src = src.replace('_p = OUT_DIR / "results.json"',
                          '_p = OUT_DIR / "real_results.json"   # NOT results.json: '
                          'that name belongs to the 77 hMOF run, and overwriting it\n'
                          '                                     # would destroy the set '
                          'this one is meant to be compared against')
        c['source'] = src.splitlines(keepends=True)

# -------------------------------------------------- new closing cells -------
cells.append(md('''---

## Step 12 — Compare against the 77-framework hypothetical band

This is the cell the whole notebook exists for. It puts the real frameworks and
the hypothetical ones on one axis and reports whether they occupy the same
region of Δα.

**Size is controlled first.** Δα rises with graph size, so a comparison between
sets of different sizes measures the size difference. Both sets are expanded
under the same `MIN_CELL_LENGTH` rule, and the cell reports the block-count
ranges so you can confirm they overlap before reading anything into the result.

To include the hMOF band, upload `results.json` from the original run next to
this notebook. Without it the cell still reports the real-MOF band on its own.
'''))

cells.append(code('''# ============================================================
# STEP 12: Real vs hypothetical, on one axis
# ============================================================
import json, numpy as np, matplotlib.pyplot as plt
from pathlib import Path

real_w  = np.array([r["width"] for r in results.values() if np.isfinite(r.get("width", np.nan))])
real_bl = np.array([r.get("n_nodes", 0) + r.get("n_linkers", 0) for r in results.values()])

# The hMOF results are optional -- upload results.json to enable the comparison.
hmof_path = next((p for p in [Path("results.json"), Path("multi_mof_output/results.json_hmof"),
                              Path("hmof_results.json")] if p.exists()), None)
hmof_w = hmof_bl = None
if hmof_path:
    _h = json.loads(hmof_path.read_text())
    hmof_w  = np.array([v["width"] for v in _h.values() if np.isfinite(v.get("width", np.nan))])
    hmof_bl = np.array([v.get("n_nodes", 0) + v.get("n_linkers", 0) for v in _h.values()])
    print(f"loaded {len(hmof_w)} hypothetical frameworks from {hmof_path}")
else:
    print("results.json (the hMOF run) not found -- reporting the real band alone.")
    print("Upload it beside this notebook to get the comparison.")

def band(x):
    q1, q3 = np.percentile(x, [25, 75])
    return dict(n=len(x), lo=float(x.min()), hi=float(x.max()),
                q1=float(q1), q3=float(q3), med=float(np.median(x)))

rb = band(real_w)
print(f"\\nREAL  (synthesised)   n={rb['n']:3d}  Δα {rb['lo']:.3f}–{rb['hi']:.3f}"
      f"  IQR {rb['q1']:.3f}–{rb['q3']:.3f}  median {rb['med']:.3f}")
print(f"      blocks {real_bl.min()}–{real_bl.max()}")

if hmof_w is not None:
    hb = band(hmof_w)
    print(f"hMOF  (hypothetical)  n={hb['n']:3d}  Δα {hb['lo']:.3f}–{hb['hi']:.3f}"
          f"  IQR {hb['q1']:.3f}–{hb['q3']:.3f}  median {hb['med']:.3f}")
    print(f"      blocks {hmof_bl.min()}–{hmof_bl.max()}")

    # --- is the comparison size-fair? ---
    overlap_lo = max(real_bl.min(), hmof_bl.min())
    overlap_hi = min(real_bl.max(), hmof_bl.max())
    print(f"\\nblock-count overlap: {overlap_lo}–{overlap_hi}", end="  ")
    if overlap_hi <= overlap_lo:
        print("*** NO OVERLAP -- any Δα difference may be pure size. Do not claim a gap.")
    else:
        rm = (real_bl >= overlap_lo) & (real_bl <= overlap_hi)
        hm = (hmof_bl >= overlap_lo) & (hmof_bl <= overlap_hi)
        print(f"({rm.sum()} real, {hm.sum()} hypothetical in range)")
        if rm.sum() >= 3 and hm.sum() >= 3:
            print(f"  size-matched:  real Δα {real_w[rm].min():.3f}–{real_w[rm].max():.3f}"
                  f"   vs   hMOF {hmof_w[hm].min():.3f}–{hmof_w[hm].max():.3f}")
            gap = real_w[rm].min() - hmof_w[hm].max()
            print(f"  -> {'SEPARATED, gap %.3f' % gap if gap > 0 else 'OVERLAPPING (no gap)'}")

    # --- correlation of width with size, within each set ---
    for nm, w_, b_ in (("real", real_w, real_bl), ("hMOF", hmof_w, hmof_bl)):
        if len(w_) > 3 and b_.std() > 0:
            print(f"  r(Δα, blocks) within {nm}: {np.corrcoef(w_, b_)[0,1]:+.3f}")

# ------------------------------------------------------------------ figure --
fig, ax = plt.subplots(figsize=(9, 3.4), dpi=140)
sets = [("Synthesised (CoRE MOF)", real_w, "#b91c1c")]
if hmof_w is not None:
    sets.insert(0, ("Hypothetical (hMOF)", hmof_w, "#1d4ed8"))
for i, (label, vals, col) in enumerate(sets):
    y = len(sets) - 1 - i
    q1, q3 = np.percentile(vals, [25, 75])
    ax.plot([vals.min(), vals.max()], [y, y], color=col, lw=1.4, alpha=.55, zorder=1)
    ax.add_patch(plt.Rectangle((q1, y - .22), q3 - q1, .44,
                               facecolor=col, alpha=.16, edgecolor=col, lw=1.2, zorder=2))
    ax.plot([np.median(vals)] * 2, [y - .22, y + .22], color=col, lw=2.4, zorder=3)
    ax.scatter(vals, np.full_like(vals, y), s=13, color=col, alpha=.75, zorder=4)
    ax.text(-0.012, y, f"{label}\\nn = {len(vals)}", transform=ax.get_yaxis_transform(),
            ha="right", va="center", fontsize=9)
ax.set_yticks([]); ax.set_ylim(-.6, len(sets) - .4)
ax.set_xlabel(r"$\\Delta\\alpha$   (multifractal spectrum width)")
ax.set_title("Spectrum width: synthesised vs hypothetical frameworks", fontsize=11)
ax.grid(axis="x", alpha=.25); ax.spines[["top", "right", "left"]].set_visible(False)
plt.tight_layout()
plt.savefig(OUT_DIR / "real_vs_hypothetical.png", dpi=160, bbox_inches="tight")
plt.show()
print("\\nsaved", OUT_DIR / "real_vs_hypothetical.png")
'''))

cells.append(md('''## Step 13 — Download everything

`real_results.json` is the file to send back. The figures go on the Results page
of the project site next to the 77-framework band.
'''))

cells.append(code('''# ============================================================
# STEP 13: Download
# ============================================================
import shutil
from pathlib import Path

OUT_DIR = Path("multi_mof_output")
bundle = sorted(p for p in OUT_DIR.iterdir() if p.suffix in (".json", ".png"))
print("files produced:")
for p in bundle:
    print(f"  {p.name:38s} {p.stat().st_size/1024:8.1f} KB")

zip_path = shutil.make_archive("real_mof_results", "zip", OUT_DIR)
print(f"\\nbundled -> {zip_path}")

try:
    from google.colab import files
    files.download(zip_path)          # everything in one go
except Exception:
    print("\\nNot on Colab. Copy multi_mof_output/ off this machine manually.")
'''))

json.dump(nb, open(DST, 'w', encoding='utf-8'), indent=1)
print(f'wrote {DST}: {len(cells)} cells')
