#!/usr/bin/env python3
"""
verify_figures.py — proves every image in this repository was generated by our
own code rather than downloaded from anywhere.

WHY THIS EXISTS
"We made all the figures ourselves" is easy to say and hard to demonstrate
after the fact. A figure lifted from a paper is both a copyright problem and an
academic-integrity problem, and a reviewer is entitled to ask. This script turns
the claim into something checkable in two seconds.

HOW IT WORKS
A PNG stores metadata in `tEXt` chunks before the image data. Matplotlib writes
its own name and version into one on every `savefig`. An image downloaded from a
journal, a website or a stock library carries something else — EXIF from a
camera, an Adobe or GIMP signature, or no Software chunk at all. So the chunk is
a reliable fingerprint of what produced the file.

Run:  python verify_figures.py
Exit: 0 if everything checks out, 1 otherwise.
"""
import hashlib
import struct
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Anything matching these means the file passed through a camera or an image
# editor, which no figure of ours ever did.
FOREIGN = ("adobe", "photoshop", "gimp", "canva", "figma", "inkscape",
           "imagemagick", "screenshot", "exif")

# Figures that intentionally exist in more than one folder, and must stay
# byte-identical so a stale copy cannot disagree with the live one.
EXPECTED_DUPLICATES = ("fig01_mof_concept.png", "fig02_pipeline.png",
                       "fig03_periodic_vs_naive.png", "fig04_degeneracy.png",
                       "fig05_defect.png", "fig06_boxgrowing.png",
                       "fig07_tau_fix.png", "fig08_band77.png",
                       "fig09_real_vs_hmof.png", "fig10_real_band61.png",
                       "fig11_real_spectra61.png",
                       "band77_figure.png", "band_analysis.png")


def png_text_chunks(path):
    """Return {keyword: value} for every tEXt/iTXt chunk before the image data."""
    raw = path.read_bytes()
    if raw[:8] != b"\x89PNG\r\n\x1a\n":
        return None                      # not a PNG at all
    out, i = {}, 8
    while i < len(raw) - 8:
        length = struct.unpack(">I", raw[i:i + 4])[0]
        ctype = raw[i + 4:i + 8]
        if ctype in (b"tEXt", b"iTXt"):
            key, _, val = raw[i + 8:i + 8 + length].partition(b"\x00")
            out[key.decode("latin1")] = val.decode("latin1", "replace").strip("\x00")
        if ctype == b"IDAT":             # metadata all precedes the pixels
            break
        i += 12 + length
    return out


def main():
    images = sorted(p for p in ROOT.rglob("*.png") if ".git" not in p.parts)
    images += sorted(p for p in ROOT.rglob("*.jpg") if ".git" not in p.parts)
    images += sorted(p for p in ROOT.rglob("*.jpeg") if ".git" not in p.parts)

    if not images:
        print("No images found — nothing to verify.")
        return 0

    failures = []
    by_hash = defaultdict(list)
    by_name = defaultdict(list)

    print(f"Checking {len(images)} images under {ROOT.name}/\n")
    print(f"{'file':56s} {'size':>8s}  origin")
    print("-" * 96)

    for p in images:
        rel = p.relative_to(ROOT)
        digest = hashlib.sha256(p.read_bytes()).hexdigest()
        by_hash[digest].append(rel)
        by_name[p.name].append((rel, digest))

        if p.suffix.lower() in (".jpg", ".jpeg"):
            # We never produce JPEG. Every figure here is a line plot or a
            # diagram, and JPEG's lossy compression smears thin lines and text.
            # A JPEG in this tree is therefore almost certainly imported.
            failures.append(f"{rel}: JPEG — we only ever write PNG, so this was imported")
            print(f"{str(rel):56s} {p.stat().st_size // 1024:6d} KB  *** JPEG, NOT OURS")
            continue

        chunks = png_text_chunks(p)
        if chunks is None:
            failures.append(f"{rel}: not a valid PNG")
            print(f"{str(rel):56s} {'':8s}  *** unreadable")
            continue

        software = chunks.get("Software", "")
        blob = " ".join(chunks.values()).lower()

        foreign = [m for m in FOREIGN if m in blob]
        if foreign:
            failures.append(f"{rel}: carries {foreign} metadata — not generated by us")
            origin = f"*** FOREIGN: {foreign}"
        elif "matplotlib" in software.lower():
            origin = software
        else:
            failures.append(f"{rel}: no matplotlib signature (Software={software!r})")
            origin = f"*** UNKNOWN: {software or 'no Software chunk'}"

        print(f"{str(rel):56s} {p.stat().st_size // 1024:6d} KB  {origin}")

    # ---- duplicated figures must be byte-identical -------------------------
    print()
    print("Duplicate check — the same figure in several folders must not drift:")
    drift = False
    for name, entries in sorted(by_name.items()):
        if len(entries) < 2:
            continue
        digests = {d for _, d in entries}
        if len(digests) == 1:
            print(f"  OK   {name:34s} {len(entries)} identical copies")
        else:
            drift = True
            print(f"  FAIL {name:34s} {len(entries)} copies, {len(digests)} DIFFERENT versions:")
            for rel, d in entries:
                print(f"         {d[:12]}  {rel}")
            failures.append(f"{name}: copies have drifted apart — regenerate and re-sync")
    if not drift and not any(len(e) > 1 for e in by_name.values()):
        print("  (no duplicates)")

    # ---- verdict ------------------------------------------------------------
    print()
    if failures:
        print(f"{len(failures)} PROBLEM(S):")
        for f in failures:
            print(f"  - {f}")
        return 1

    print(f"All {len(images)} images verified: every one produced by matplotlib,")
    print("none carrying camera or image-editor metadata, no duplicates out of sync.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
